# this is how to create a secret in k8s... normally you shouldnt expose this to the public
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: YWRtaW4=
  mongo-root-password: cGFzc3dvcmQ=
# you base64 encode the username and password you want to store
