pipeline {
	agent any
	tools {
		go 'go-1.17'
	}

	environment {
		GO111MODULE='on'
	}

	stages {
		stage('Test') {
			steps {
				git 'https://github.com/Chxnedu/go-webapp-sample.git'
				sh 'go test ./...'
			}
		}
		stage('Building our image') {
			steps {
				script {
					app = docker.build("chxnedu/go-webapp-sample")
				}
			}
		}
	}
}



