# kube deployment yaml config file format

apiversion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
# this tells the deployment how to match the service to it 
      app: nginx
  template:
# template contains the config for the pods, thats why it has metadata and spec
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16
        ports:
        - containerPort: 8080

# so now when you create a config file for service, you specify the app: nginx in the selector
